### ISSUE TITLE
반응형 사이트로 바꾸기

### ISSUE THREAD

**Issue by hanbyul9** [younme20/ynm#33]
반응형 사이트로 바꾸기

**Comment by hanbyul9** [comment]
1. tiles-header.jsp 부분에 컨텍스트 패스 일괄 수정한 부분이 반영 안된 곳이 있으니 확인부탁드려요.(기존 하드코딩에서 <c:url~ 로 변경)
2. 수정 파일 중 반영 안된 파일이 있는지 확인 후 다시 커밋 부탁드립니다. 로그인, 스케쥴 확인 하는 부분이 보이지 않습니다. 전체적으로 이전 커밋에 반영된 부분이 많이 누락된 듯 합니다. 
3. application.properties 에 깃헙 토큰은 커밋할 시 제외해주세요.

**Comment by Bang04** [comment]
반응형 적용 완료

**Comment by Bang04** [comment]
반응형 적용 완료(마스터+서버)
